default:
  ingestion:
    kobo:
      asset_id: !expr Sys.getenv('KOBO_ASSET_ID')
      username: !expr Sys.getenv('KOBO_USERNAME')
      password: !expr Sys.getenv('KOBO_PASSWORD')
      token: !expr Sys.getenv('KOBO_TOKEN')
    surveys:
      raw:
        file_prefix: "raw-surveys"
      preprocessed:
        file_prefix: "preprocessed-surveys"
      darwincore:
        file_prefix: "dc-formatted-surveys"
    tidy_data:
      file_prefix: "tidy-data"
  storage:
    sharepoint:
      buckets:
        automation_bucket: zoogon_mc-dev
        legacy_bucket: legacy_data
        hot_bucket: hot_storage
        unmatched_bucket: worms_unmatched
        darwin_core_bucket: darwincore_archives
        reports_bucket: reports
      credentials:
        site_url: "https://sznit.sharepoint.com/sites/BioFlow-ZOOGoN-40Y"
        client_id: !expr Sys.getenv('SHAREPOINT_CLIENT_ID')
        tenant_id: !expr Sys.getenv('SHAREPOINT_TENANT_ID')
        client_secret: !expr Sys.getenv('SHAREPOINT_CLIENT_SECRET')

production:
  storage:
    sharepoint:
      automation_bucket: zoogon_mc-prod
